import React from 'react';

interface TermsOfServiceProps {
    onBack: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
    const lastUpdated = "October 26, 2023";

    return (
        <div className="p-6 overflow-y-auto h-full text-gray-800">
            <div className="prose max-w-full prose-headings:text-gray-800 prose-p:text-gray-700 prose-li:text-gray-700">
                <h1 className="text-2xl sm:text-3xl font-bold mb-4">Terms of Service – GROWit</h1>
                <p className="text-sm text-gray-600"><strong>Last Updated:</strong> {lastUpdated}</p>
                
                <h2 className="text-2xl font-semibold mt-6">1. Introduction</h2>
                <p>These Terms of Service ("Terms") govern your use of the GROWit application ("Service") operated by us. By accessing or using our Service, you agree to be bound by these Terms.</p>
                
                <h2 className="text-2xl font-semibold mt-6">2. Use of Service</h2>
                <p>You agree not to use the Service for any unlawful purpose or to violate any laws in your jurisdiction. You are responsible for any text, data, or other materials ("Content") that you submit to the Service.</p>
                <p>Prohibited actions include: attempting to interfere with the Service's network or security features, using the Service to generate hateful or illegal content, and attempting to reverse-engineer the application.</p>
                
                <h2 className="text-2xl font-semibold mt-6">3. Intellectual Property</h2>
                <p>The Service and its original content, features, and functionality are and will remain the exclusive property of GROWit and its licensors. You are granted a limited, non-exclusive, non-transferable license to use the Service for your personal or internal business purposes.</p>

                <h2 className="text-2xl font-semibold mt-6">4. Disclaimer and No Warranty</h2>
                <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. GROWit makes no warranty that the Service will meet your requirements, be available on an uninterrupted, secure, or error-free basis, or that the results obtained from the use of the Service will be accurate or reliable.</p>
                <p>We do not guarantee any specific results, such as viral growth or increased engagement, from using the content generated by our Service.</p>

                <h2 className="text-2xl font-semibold mt-6">5. Limitation of Liability</h2>
                <p>In no event shall GROWit, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
                
                <h2 className="text-2xl font-semibold mt-6">6. Termination</h2>
                <p>We may terminate or suspend your access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

                <h2 className="text-2xl font-semibold mt-6">7. Changes to Terms</h2>
                <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.</p>

                <h2 className="text-2xl font-semibold mt-6">8. Governing Law</h2>
                <p>These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which the company is established, without regard to its conflict of law provisions.</p>
                
                <h2 className="text-2xl font-semibold mt-6">9. Contact Information</h2>
                <p>If you have any questions about these Terms, please contact us at support@growit.example.com.</p>
            </div>
             <div className="text-center mt-8">
                <button onClick={onBack} className="px-6 py-2 font-bold text-white bg-gradient-to-r from-blue-500 to-green-500 rounded-lg shadow-lg">
                    &larr; Back to App
                </button>
            </div>
        </div>
    );
};